site: {
  url: "https://blog.bibliyorlar.com/",
  title: "Bibliyorlar",
  description: "Bibliyorlar – teknoloji, internet, oyun, yaşam ve daha fazlası.",
  author: "Bibliyorlar",
  profile: "https://bibliyorlar.com",
  ogImage: "default-og.jpg",
  lang: "tr",
  timezone: "Europe/Istanbul",
  dir: "ltr",
},
